"""Added Association Table Meal_Card

Revision ID: 283305d5933f
Revises: 0a0576b0329c
Create Date: 2023-12-14 02:22:41.259043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283305d5933f'
down_revision = '0a0576b0329c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_card',
    sa.Column('barista_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barista_id'], ['baristas.barista_id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_card')
    # ### end Alembic commands ###
