"""Added Association Class Meal_Cards and Table

Revision ID: a4c86dbd9af2
Revises: 022558d08779
Create Date: 2023-12-14 04:13:24.167740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c86dbd9af2'
down_revision = '022558d08779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_card',
    sa.Column('meal_card_id', sa.Integer(), nullable=True),
    sa.Column('meal_served', sa.VARCHAR(length=40), nullable=True),
    sa.Column('specifications', sa.VARCHAR(length=40), nullable=True),
    sa.Column('satisfaction_rank', sa.Integer(), nullable=True),
    sa.Column('comments', sa.VARCHAR(length=40), nullable=True),
    sa.Column('barista_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barista_id'], ['baristas.barista_id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], )
    )
    op.create_table('meals',
    sa.Column('meal_card_id', sa.Integer(), nullable=False),
    sa.Column('meal_served', sa.VARCHAR(length=40), nullable=True),
    sa.Column('specifications', sa.VARCHAR(length=40), nullable=True),
    sa.Column('satisfaction_rank', sa.Integer(), nullable=True),
    sa.Column('comments', sa.VARCHAR(length=40), nullable=True),
    sa.Column('barista_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barista_id'], ['baristas.barista_id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('meal_card_id')
    )
    op.drop_table('meal_cards')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_cards',
    sa.Column('meal_card_id', sa.INTEGER(), nullable=True),
    sa.Column('meal_served', sa.VARCHAR(length=40), nullable=True),
    sa.Column('specifications', sa.VARCHAR(length=40), nullable=True),
    sa.Column('satisfaction_rank', sa.INTEGER(), nullable=True),
    sa.Column('comments', sa.VARCHAR(length=40), nullable=True),
    sa.Column('barista_id', sa.INTEGER(), nullable=True),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['barista_id'], ['baristas.barista_id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], )
    )
    op.drop_table('meals')
    op.drop_table('meal_card')
    # ### end Alembic commands ###
